// • 1. Crear un array de objetos con al menos 15 productos (helados). Cada objeto debe tener:
// nombre, sabor, precio, stock, categoría y estado (activo o descontinuado).
// • 2. Mostrar todos los productos en consola usando forEach.

let hela2=[
    {
        nombre: "Iron Mango",
        sabor: "Mango y nuez",
        precio: 20,
        stock: 110,
        categoria: "marvel",
        estado: "activo",
    },
    {
        nombre: "Helado Oscuro",
        sabor: "mora y uva",
        precio: 50,
        stock: 50,
        categoria: "star wars",
        estado: "activo",
    },
    {
        nombre: "Cerveza de mantequilla",
        sabor: "vainilla y caramelo",
        precio: 70,
        stock: 9,
        categoria: "harry potter",
        estado: "inactivo",
    },
    {
        nombre: "Heladolnir",
        sabor: "morazul y chicle",
        precio: 10,
        stock: 4,
        categoria: "marvel",
        estado: "inactivo",
    },
    {
        nombre: "Cerebro de sapo",
        sabor: "Limon y Feijoa",
        precio: 15,
        stock: 200,
        categoria: "harry potter",
        estado: "activo",
    },
    {
        nombre: "Fresa Imperial",
        sabor: "Frutos Rojos",
        precio: 17,
        stock: 30,
        categoria: "star wars",
        estado: "activo",
    },
    {
        nombre: "Macadamia de la republica",
        sabor: "vainilla y galleta",
        precio: 24,
        stock: 36,
        categoria: "star wars",
        estado: "activo",
    },
    {
        nombre: "Acihulk",
        sabor: "Limon intenso",
        precio: 32,
        stock: 520,
        categoria: "marvel",
        estado: "inactivo",
    },
    {
        nombre: "Heladoriano",
        sabor: "Vainilla y limon",
        precio: 32,
        stock: 64,
        categoria: "star wars",
        estado: "activo",
    },
    {
        nombre: "Feliz Felicis",
        sabor: "Hierbabuena y limon",
        precio: 12,
        stock: 65,
        categoria: "harry potter",
        estado: "inactivo",
    },
    {
        nombre: "Helatroll",
        sabor: "feijoa y chocolate",
        precio: 23,
        stock: 2,
        categoria: "harry potter",
        estado: "activo",
    },
    {
        nombre: "Ant-ellana",
        sabor: "Avellana y vainilla",
        precio: 12,
        stock: 4,
        categoria: "marvel",
        estado: "activo",
    },
    {
        nombre: "Sith-dia",
        sabor: "Sandia y frutos rojos",
        precio: 15,
        stock: 30,
        categoria: "star wars",
        estado: "activo",
    },
    {
        nombre: "Aranda kedavra",
        sabor: "Arandano, nuez y vainilla",
        precio: 32,
        stock: 50,
        categoria: "harry potter",
        estado: "activo",
    },
    {
        nombre: "Viuda verde",
        sabor: "feijoa y galleta",
        precio: 21,
        stock: 40,
        categoria: "marvel",
        estado: "inactivo",
    },
];

hela2.forEach(console.log);
